formats:
  - oas2
  - oas3
extends:
  - 'spectral:oas'
functions:
  - abc
rules:
  my-rule:
    message: '{{error}}'
    given: $.info
    then:
      function: abc
    severity: error
  info-matches-stoplight:
    description: This is an example rule
    message: Info must contain Stoplight
    given: $.info
    recommended: true
    type: style
    then:
      field: title
      function: pattern
      functionOptions:
        match: Stoplight
