openapi: 3.0.0
info:
  title: axway
  version: '1.0'
  contact:
    name: a
  description: a
servers:
  - url: 'http://localhost:3000'
paths:
  /getstuff:
    get:
      summary: aa
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: foo
                $ref: ../todos/models/user.v1.json
      description: a
components:
  schemas: {}
