openapi: 3.0.0
info:
  version: 3.0.0
  title: Swagger Petstore
  license:
    name: MIT
  description: Petstore.
servers:
  - url: 'http://localhost:4010'
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: ./models/pet.v1.yaml
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      tags:
        - Endpoints
        - Petstore
      description: ''
    post:
      summary: Create a pet
      operationId: createPets
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      tags:
        - Endpoints
        - Petstore
      description: ''
    patch:
      summary: ''
      responses:
        '200':
          description: OK
  '/pets/{petId}':
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - Endpoints
        - Petstore
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: ./models/pet.v1.yaml
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
    head:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'http://localhost:8080/api/nodes.raw?srn=gh/dgrstl/studio-demo/reference/petstore/openapi.yaml/components/schemas/Pets&mid=1'
components:
  schemas:
    Pets:
      type: array
      items:
        $ref: ./models/pet.v1.yaml
      title: Pets
      description: A list of pets.
      x-tags:
        - Models
        - Petstore
